apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    reconcile.fluxcd.io/watch: Enabled
configMapGenerator:
- name: headlamp-values
  namespace: flux-system
  files:
  - values.yaml
resources:
- release.yaml  
- repo.yaml
